# Generated by Django 4.0.6 on 2022-08-13 09:03

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('car_rent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='phone_regex',
            field=models.CharField(default=django.utils.timezone.now, max_length=17, verbose_name=django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+00 000 000 000'. Up to 11 digits allowed.", regex='(^[+]\\d+(?:[ ]\\d+)*)')),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=17, verbose_name=django.core.validators.RegexValidator(message="Phone nr must be entered in the format: +00 000 000 000'. Up to 11 digits allowed.", regex='(^[+]\\d+(?:[ ]\\d+)*)')),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='customer',
            name='credit_card_nr',
            field=models.IntegerField(),
        ),
    ]
