# Generated by Django 4.0.6 on 2022-08-10 18:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('surname', models.CharField(max_length=30, verbose_name='surname')),
                ('address', models.CharField(max_length=39)),
                ('company', models.CharField(max_length=50, null=True)),
                ('credit_card_nr', models.IntegerField(max_length=24)),
                ('tax_id', models.CharField(max_length=10, null=True)),
                ('mobile', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone nr must be entered in the format: +00 000 000 000'. Up to 11 digits allowed.", regex='(^[+]\\d+(?:[ ]\\d+)*)')])),
                ('email', models.EmailField(max_length=39)),
            ],
        ),
    ]
