# Generated by Django 4.0.6 on 2022-08-06 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_rent', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentaloffer',
            old_name='BranchCarAvailabilityId',
            new_name='BranchCarAvailability_Id',
        ),
        migrations.RemoveField(
            model_name='rentaloffer',
            name='Availability',
        ),
        migrations.CreateModel(
            name='CarAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Availability', models.CharField(max_length=16)),
                ('Vehicle_Id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='car_rent.vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='rentaloffer',
            name='CarAvailability_Id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='car_rent.caravailability'),
            preserve_default=False,
        ),
    ]
