# Generated by Django 4.0.6 on 2022-08-06 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_rent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=39)),
                ('city', models.CharField(max_length=16)),
                ('mobile', models.CharField(max_length=15)),
                ('opening_hours', models.CharField(max_length=39)),
                ('mail', models.EmailField(max_length=39)),
                ('remarks', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BranchCarAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Branch_Id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='car_rent.branch')),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='car_rent.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_year', models.IntegerField(max_length=4)),
                ('color', models.CharField(max_length=16)),
                ('engine', models.DecimalField(decimal_places=1, max_digits=2)),
                ('type_of_fuel', models.CharField(max_length=16)),
                ('transmission', models.CharField(max_length=16)),
                ('mileage', models.DecimalField(decimal_places=1, max_digits=7)),
                ('vin', models.IntegerField(max_length=17)),
                ('photo', models.TextField(null=True)),
                ('car_description', models.TextField(null=True)),
                ('body_type_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='car_rent.bodytype')),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='car_rent.model')),
            ],
        ),
        migrations.CreateModel(
            name='RentalOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Availability', models.CharField(max_length=4, null=True)),
                ('Categories', models.CharField(max_length=16)),
                ('Description', models.TextField(null=True)),
                ('Deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('BranchCarAvailabilityId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='car_rent.branchcaravailability')),
                ('Vehicle_Id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='car_rent.vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='branchcaravailability',
            name='Vehicle_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='car_rent.vehicle'),
        ),
    ]
