# Generated by Django 4.0.6 on 2022-08-10 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_rent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=39)),
                ('surname', models.CharField(max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_renting',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='branchcaravailability',
            name='availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='rentaloffer',
            name='Categories',
            field=models.CharField(choices=[('Economy', 'Economy'), ('Intermediate ', 'Intermediate '), ('Premium', 'Premium'), ('Luxury', 'Luxury')], max_length=13),
        ),
        migrations.CreateModel(
            name='CarRental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('date_of_rent', models.DateField(auto_now_add=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='car_rent.customer')),
                ('rental_offer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='car_rent.rentaloffer')),
            ],
        ),
    ]
