# Generated by Django 4.0.6 on 2022-08-07 08:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('car_rent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='prod_year',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='type_of_fuel',
            field=models.CharField(choices=[('Diesel', 'Diesel'), ('Gasoline', 'Gasoline'), ('Hybrid', 'Hybrid'), ('Electric', 'Electric')], max_length=16),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(max_length=17),
        ),
    ]
