# Generated by Django 4.0.6 on 2022-08-07 09:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('car_rent', '0002_alter_vehicle_photo_alter_vehicle_prod_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='body_type_id',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='car_description',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='body_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='type_of_fuel',
            field=models.CharField(max_length=16),
        ),
        migrations.DeleteModel(
            name='BodyType',
        ),
    ]
