# Generated by Django 4.0.6 on 2022-08-07 08:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('car_rent', '0002_rename_branch_id_branchcaravailability_branch_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchcaravailability',
            name='availability',
            field=models.BooleanField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
