# Generated by Django 4.0.6 on 2022-07-31 13:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('car_rent', '0002_bodytype_branch_brand_model_vehicle_rentaloffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='Vehicle_Id',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.PROTECT, to='car_rent.vehicle'),
            preserve_default=False,
        ),
    ]
