# Generated by Django 4.0.6 on 2022-08-14 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_rent', '0003_branch_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchCarAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.BooleanField(default=True)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='car_rent.branch')),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='car_rent.vehicle')),
            ],
        ),
    ]
