# Generated by Django 4.0.6 on 2022-08-14 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_rent', '0004_branchcaravailability'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(choices=[], max_length=24)),
                ('Categories', models.CharField(choices=[('Economy', 'Economy'), ('Intermediate ', 'Intermediate '), ('Premium', 'Premium'), ('Luxury', 'Luxury')], max_length=13)),
                ('Description', models.TextField(null=True)),
                ('Deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('BranchCarAvailability_Id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='car_rent.branchcaravailability')),
                ('Vehicle_Id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='car_rent.vehicle')),
            ],
        ),
    ]
