# Generated by Django 4.0.6 on 2022-08-14 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_rent', '0005_rentaloffer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarRental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('date_of_rent', models.DateField(auto_now_add=True)),
                ('is_rented', models.BooleanField(default=False)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('rental_offer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='car_rent.rentaloffer')),
            ],
        ),
    ]
