# Generated by Django 4.0.6 on 2022-08-17 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_rent', '0006_carrental'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentaloffer',
            name='model',
        ),
    ]
