# Generated by Django 4.0.6 on 2022-08-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rent', '0007_remove_rentaloffer_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='saldo',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
