# Generated by Django 4.0.6 on 2022-08-18 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_rent', '0008_customuser_saldo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='saldo',
            new_name='balance',
        ),
    ]
