# Generated by Django 4.0.6 on 2022-08-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rent', '0009_rename_saldo_customuser_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='balance',
            field=models.DecimalField(decimal_places=1, max_digits=10, null=True),
        ),
    ]
