# Generated by Django 4.0.6 on 2022-08-19 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rent', '0010_alter_customuser_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='company',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='tax_id',
        ),
        migrations.AddField(
            model_name='customuser',
            name='CVV',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='expiration',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='house_number',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='street',
            field=models.CharField(max_length=39, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='zip_code',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='credit_card_nr',
            field=models.CharField(max_length=39, null=True),
        ),
    ]
