# Generated by Django 4.0.6 on 2022-08-24 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rent', '0011_remove_customuser_address_remove_customuser_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentaloffer',
            name='BranchCarAvailability_Id',
        ),
        migrations.AlterField(
            model_name='branch',
            name='open_from',
            field=models.CharField(choices=[('05', '05:00'), ('06', '06:00'), ('07', '07:00'), ('08', '08:00'), ('09', '09:00'), ('10', '10:00'), ('11', '11:00'), ('12', '12:00')], max_length=6),
        ),
        migrations.AlterField(
            model_name='branch',
            name='open_till',
            field=models.CharField(choices=[('13', '13:00'), ('14', '14:00'), ('15', '15:00'), ('16', '16:00'), ('17', '17:00'), ('18', '18:00'), ('19', '19:00'), ('20', '20:00'), ('21', '21:00'), ('22', '22:00'), ('23', '23:00')], max_length=6),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vin',
            field=models.CharField(max_length=17, unique=True),
        ),
        migrations.DeleteModel(
            name='BranchCarAvailability',
        ),
    ]
