# Generated by Django 4.0.6 on 2022-08-25 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_rent', '0013_alter_customuser_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentaloffer',
            name='Vehicle_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='car_rent.vehicle', unique=True),
        ),
    ]
