# Generated by Django 4.0.6 on 2022-08-25 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_rent', '0014_alter_rentaloffer_vehicle_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentaloffer',
            name='Vehicle_Id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='car_rent.vehicle'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='engine',
            field=models.CharField(choices=[('1.3', '1.3'), ('1.9', '1.9'), ('2.4', '2.4'), ('3.0', '3.0'), ('4.4', '4.4'), ('5.4', '5.4')], max_length=3),
        ),
    ]
